name       : perl-autovivification
version    : '0.18'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/V/VP/VPIT/autovivification-0.18.tar.gz : 2d99975685242980d0a9904f639144c059d6ece15899efde4acb742d3253f105
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Lexically disable autovivification
description: |
    Lexically disable autovivification
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
