name       : perl-autovivification
version    : 0.16
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/V/VP/VPIT/autovivification-0.16.tar.gz : 814d0ef1fc6f01dbd0b85ffbec474b66d581c3a3ceb537e5ca67dbe9129f4290
license    : GPL-2.0
component  : programming.perl
summary    : Lexically disable autovivification
description: |
    Lexically disable autovivification
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
